name: Build and Push SealDice Docker Images

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (pre-release/stable)'
        required: false
        default: 'stable'
  repository_dispatch:

env:
  DOCKERHUB_REPO: shiaworkshop/sealdice

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: 确定构建类型
        id: determine_type
        run: |
          if [ "${{ github.event.inputs.build_type || 'stable' }}" != "auto" ]; then
            BUILD_TYPE="${{ github.event.inputs.build_type || 'stable' }}"
          else
            if [ -f "last_release.json" ]; then
              BUILD_TYPE="stable"
            elif [ -f "pre_release.json" ]; then
              BUILD_TYPE="pre-release"
            else
              echo "找不到版本信息文件"
              exit 1
            fi
          fi
          echo "最终构建类型: $BUILD_TYPE"
          echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
          echo "CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV
          
          if [ "$BUILD_TYPE" = "pre-release" ]; then
            CONFIG_FILE="pre_release.json"
          else
            CONFIG_FILE="last_release.json"  # 您的稳定版配置文件实际名称
          fi
      
      - name: 获取版本标签
        id: get_version
        run: |
          case "$BUILD_TYPE" in
            "pre-release")
              # 从JSON文件获取提交哈希的前7位
              COMMIT_TAG=$(jq -r '.commit_hash[0:7]' $CONFIG_FILE)
              ;;
            "stable")
              # 从JSON文件获取完整版本号
              COMMIT_TAG=$(jq -r '.tag_name' $CONFIG_FILE)
              ;;
            *)
              echo "不支持的构建类型: $BUILD_TYPE"
              exit 1
              ;;
          esac
          
          echo "COMMIT_TAG=$COMMIT_TAG" >> $GITHUB_ENV
          echo "MAIN_TAG=$BUILD_TYPE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_TYPE=${{ env.BUILD_TYPE }}
            CONFIG_FILE=${{ env.CONFIG_FILE }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.MAIN_TAG }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.COMMIT_TAG }}
            ${{ env.DOCKERHUB_REPO }}:latest
